name: Build and Deploy

on:
  push:
    branches: [ 0.8.X ]
  pull_request:
    branches: [ 0.8.X ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build with Node.js
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app/ruoyi-ui node:16-alpine3.16 sh -c "npm install && npm run build:prod"
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: ruoyi-ui/dist
