name: Build and Deploy

on:
  push:
    branches: [ 0.8.X ]
  pull_request:
    branches: [ 0.8.X ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        cd ruoyi-ui
        npm install
      env:
        CI: true
