name: Build and Deploy

on:
  push:
    branches: [ 0.8.X ]
  pull_request:
    branches: [ 0.8.X ]

jobs:

  build:
    runs-on: node:16-alpine3.16

    steps:
    - uses: actions/checkout@v3
    - name: 编译项目
      run: |
        cd ruoyi-ui
        npm install
        npm run build:prod
      env:
        CI: true
    - name: 上传编译目录
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: ruoyi-ui/dist
