name: 编译代码

on:
  push:
    branches: [ 0.8.X ]
  pull_request:
    branches: [ 0.8.X ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 安装nodejs-16环境
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: 安装依赖和编译代码
      run: |
        cd ruoyi-ui
        npm install && npm run build:prod

    - name: 上传dist文件
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: ruoyi-ui/dist
